### ISSUE TITLE
mips support (replace or fix ring)

### ISSUE THREAD

**Issue by aep** [geeny/linux-hub-sdk#1]
the project depends on ring, which doesn't support mips

https://github.com/briansmith/ring/issues/562

i suppose a "hub" is a PC rather than an embedded device then?

**Comment by jamesmunns** [comment]
Hey Arvid,

Thanks for pointing this out. We have been using the Hub SDK mainly on ARM9 (ARMv5) and Cortex-A devices (ARMv6/ARMv7) devices so far, so this hasn't been an issue yet, but you are right, this could be a blocker for anyone on a MIPS platform.

The ring dependency comes from the optional REST API feature which uses Rocket, (`--feature="rest-service", as seen [here](https://github.com/geeny/linux-hub-sdk/blob/release/Cargo.toml#L38)), which allows you to use the Hub SDK as a standalone Linux service. If you're interested in using the SDK for now on a MIPS platform, you should still be able to use it as a Rust crate without the Rocket-based web interface.

In the future, we do want to enable more ways to use the Hub SDK, including Linux sockets, as well as via FFI bindings (for static or dynamic linking), though those are still in the works. I'll leave this issue open until we have a better way for non-rust-using MIPS developers to use the Hub SDK.

Thanks again for the feedback!
-James

**Comment by aep** [comment]
well, it should be trivial to replace rocket with hyper, which would also make it work on stable

**Comment by aep** [comment]
@bkchr

**Comment by jamesmunns** [comment]
It would absolutely be possible. @diegoeche, is this something you would be interested in?

The use of Nightly hadn't been seen as a blocker (yet), as a nightly compiler is generally necessary for cross compilation in Rust. Our internal CI is using the nightly from `2017-10-14`, which should probably be captured in the readme.

Further comments or PRs are definitely welcome.

**Comment by diegoeche** [comment]
@jamesmunns 

Yes, totally. I'd love to not depend on *cross* since not all the toolchains are supported. Also rather have stable compilation support. I'm still using the current version for the RPI image, but this could be a nice side project to get deeper into rust :)

**Comment by aep** [comment]
rocket 0.3.0 doesn't compile for me on  nightly-2017-10-14

@bkchr did it work for you?

```
cargo  +nightly-2017-10-14 build --bin hub-service --features="rest-service"
error[E0615]: attempted to take value of method `lo` on type `syntax_pos::Span`
  --> Rocket/codegen/src/utils/span_ext.rs:22:14
   |
22 |         self.lo = self.lo + BytePos(length as u32);
   |              ^^
   |
   = help: maybe a `()` to call it is missing?

```

**Comment by jamesmunns** [comment]
@aep I can't reproduce what you showed here, and it also works on our internal CI.

```
➜  linux-hub-sdk git:(release) cargo  +nightly-2017-10-14 build --bin hub-service --features="rest-service"
   Compiling hub-sdk v0.4.2 (file:///tmp/linux-hub-sdk)
    Finished dev [unoptimized + debuginfo] target(s) in 118.65 secs
➜  linux-hub-sdk git:(release) git rev-parse HEAD
5f54e2bb46511c4ed7d3ed04dc6cf2cee2cfc5df
➜  linux-hub-sdk git:(release) git status
On branch release
Your branch is up to date with 'origin/release'.
nothing to commit, working tree clean
➜  linux-hub-sdk git:(release) uname -a
Linux archx1cv4 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
```

I've also captured the `Cargo.lock` generated by this clean build, in case there is some kind of dependency mismatch. You may want to try diffing it with the Cargo.lock you generated: https://gist.github.com/jamesmunns/e58aaa4b078315fbf29d802dae143c34

**Comment by aep** [comment]
thanks, the lock helped. works with 0.3.3 rather than 0.3.0.

here's a temporary workaround to make it compile on mips
https://github.com/aep/linux-hub-sdk/blob/master/Rocket/lib/src/http/cookies.rs#L10

still failing linking zlib, will publish a binary maybe later today

**Comment by jamesmunns** [comment]
Thanks for the report! I'll make changes to the toml to pin the rocket versions, as well as update the readme to include the nightly used by our CI.

We don't generally check in the lock file, since this crate can also be used as a lib, not just a binary.
